"""
    _ephemerides_parent_point(point)

Return the SPK tree parent used by common DE planetary ephemerides.

SPICE automatically chains SPK segments. Ephemerides.jl only exposes queried
segments, so planet-center IDs such as `199` may need to be formed from their
planetary barycenter plus the center offset:

    0 -> 1 -> 199

The Earth and Moon are similarly chained through the Earth-Moon barycenter:

    0 -> 3 -> 399
    0 -> 3 -> 301

These manual helpers are retained as a provider-only fallback.  The preferred
path for arbitrary target/center queries is the `FrameTransformations.FrameSystem`
method below, because FrameTransformations.jl is the documented way to compose
Ephemerides.jl point chains.
"""
@inline function _ephemerides_parent_point(point::Int)
    if point == 301 || point == 399
        return 3
    elseif point in (199, 299, 499, 599, 699, 799, 899, 999)
        return div(point, 100)
    else
        return nothing
    end
end


@inline _ephemerides_direct_ssb_point(point::Int) = point == 10 || 1 <= point <= 9


@inline function _ephemerides_common_ssb_chain_point(point::Int)
    return point == 0 || _ephemerides_direct_ssb_point(point) || !isnothing(_ephemerides_parent_point(point))
end


"""
    _ephem_vector3_wrt_ssb(provider, point, et)

Return the position of `point` with respect to the solar-system barycenter.

Common DE ephemeris chains are evaluated deterministically to avoid throwing and
catching exceptions inside dynamics hot loops. Generic points fall back to a
direct `0 -> point` query and then to the parent-barycenter chain when possible.
"""
function _ephem_vector3_wrt_ssb(provider, point::Int, et::Number)
    point == 0 && return zeros(3)

    if _ephemerides_direct_ssb_point(point)
        return Ephemerides.ephem_vector3(provider, 0, point, et)
    end

    parent = _ephemerides_parent_point(point)
    if !isnothing(parent)
        parent_ssb = _ephem_vector3_wrt_ssb(provider, parent, et)
        point_parent = Ephemerides.ephem_vector3(provider, parent, point, et)
        return parent_ssb + point_parent
    end

    return Ephemerides.ephem_vector3(provider, 0, point, et)
end


"""
    _ephem_vector6_wrt_ssb(provider, point, et)

Return the state of `point` with respect to the solar-system barycenter.
"""
function _ephem_vector6_wrt_ssb(provider, point::Int, et::Number)
    point == 0 && return zeros(6)

    if _ephemerides_direct_ssb_point(point)
        return Ephemerides.ephem_vector6(provider, 0, point, et)
    end

    parent = _ephemerides_parent_point(point)
    if !isnothing(parent)
        parent_ssb = _ephem_vector6_wrt_ssb(provider, parent, et)
        point_parent = Ephemerides.ephem_vector6(provider, parent, point, et)
        return parent_ssb + point_parent
    end

    return Ephemerides.ephem_vector6(provider, 0, point, et)
end


"""
    _ephem_vector3_wrt_bridge(provider, point, bridge, et)

Return the position of `point` with respect to `bridge`.
"""
function _ephem_vector3_wrt_bridge(provider, point::Int, bridge::Int, et::Number)
    point == bridge && return zeros(3)

    try
        return Ephemerides.ephem_vector3(provider, bridge, point, et)
    catch
        point_ssb = _ephem_vector3_wrt_ssb(provider, point, et)
        bridge_ssb = _ephem_vector3_wrt_ssb(provider, bridge, et)
        return point_ssb - bridge_ssb
    end
end


"""
    _ephem_vector3_with_fallback(provider, from, to, et)

Query an Ephemerides.jl position vector with SPK segment-chain fallbacks.

For common DE ephemerides, known SSB/planet-barycenter chains are evaluated
before trying direct arbitrary segment queries. This provider-only path is kept
for backward compatibility.  New code should prefer the FrameTransformations
methods of `get_pos_ephemerides`, which use the point graph generated by
`build_ephemerides_frame_system`.
"""
function _ephem_vector3_with_fallback(provider, from::Int, to::Int, et::Number)
    from == to && return zeros(3)

    if _ephemerides_common_ssb_chain_point(from) && _ephemerides_common_ssb_chain_point(to)
        try
            from_ssb = _ephem_vector3_wrt_ssb(provider, from, et)
            to_ssb = _ephem_vector3_wrt_ssb(provider, to, et)
            return to_ssb - from_ssb
        catch
            # Fall through to the generic direct/bridge logic below. This keeps
            # useful errors for IDs whose NAIF code exists but whose SPK segment
            # is not available in the loaded kernel set, such as 499 with DE440
            # alone.
        end
    end

    direct_error = nothing

    try
        return Ephemerides.ephem_vector3(provider, from, to, et)
    catch error
        direct_error = error
    end

    try
        from_ssb = _ephem_vector3_wrt_ssb(provider, from, et)
        to_ssb = _ephem_vector3_wrt_ssb(provider, to, et)
        return to_ssb - from_ssb
    catch
    end

    try
        bridge = 3  # Earth-Moon barycenter
        from_bridge = _ephem_vector3_wrt_bridge(provider, from, bridge, et)
        to_bridge = _ephem_vector3_wrt_bridge(provider, to, bridge, et)
        return to_bridge - from_bridge
    catch
        throw(direct_error)
    end
end


"""
    _ephem_vector6_wrt_bridge(provider, point, bridge, et)

Return the state of `point` with respect to `bridge`.
"""
function _ephem_vector6_wrt_bridge(provider, point::Int, bridge::Int, et::Number)
    point == bridge && return zeros(6)

    try
        return Ephemerides.ephem_vector6(provider, bridge, point, et)
    catch
        point_ssb = _ephem_vector6_wrt_ssb(provider, point, et)
        bridge_ssb = _ephem_vector6_wrt_ssb(provider, bridge, et)
        return point_ssb - bridge_ssb
    end
end


"""
    _ephem_vector6_with_fallback(provider, from, to, et)

Query an Ephemerides.jl state vector with SPK segment-chain fallbacks.
"""
function _ephem_vector6_with_fallback(provider, from::Int, to::Int, et::Number)
    from == to && return zeros(6)

    if _ephemerides_common_ssb_chain_point(from) && _ephemerides_common_ssb_chain_point(to)
        try
            from_ssb = _ephem_vector6_wrt_ssb(provider, from, et)
            to_ssb = _ephem_vector6_wrt_ssb(provider, to, et)
            return to_ssb - from_ssb
        catch
            # Fall through to the generic direct/bridge logic below.
        end
    end

    direct_error = nothing

    try
        return Ephemerides.ephem_vector6(provider, from, to, et)
    catch error
        direct_error = error
    end

    try
        from_ssb = _ephem_vector6_wrt_ssb(provider, from, et)
        to_ssb = _ephem_vector6_wrt_ssb(provider, to, et)
        return to_ssb - from_ssb
    catch
    end

    try
        bridge = 3  # Earth-Moon barycenter
        from_bridge = _ephem_vector6_wrt_bridge(provider, from, bridge, et)
        to_bridge = _ephem_vector6_wrt_bridge(provider, to, bridge, et)
        return to_bridge - from_bridge
    catch
        throw(direct_error)
    end
end


"""

    get_pos_ephemerides(provider, target_id, center_id, et)

Query a target body's position relative to a center body using Ephemerides.jl.

This provider-only method is retained for backward compatibility and manually
chains common DE ephemeris point trees.  For arbitrary target/center pairs in the
dynamics, prefer the `FrameTransformations.FrameSystem` method below.
"""
function get_pos_ephemerides(provider, target_id::Integer, center_id::Integer, et::Number)
    isnothing(provider) && error(
        "No Ephemerides.jl provider was supplied. Pass `ephemerides_provider` or `ephemerides_files` to HighFidelityEphemerisModelParameters."
    )

    return _ephem_vector3_with_fallback(provider, Int(center_id), Int(target_id), et)
end


function get_pos_ephemerides(provider, target_id::String, center_id::String, et::Number)
    return get_pos_ephemerides(provider, parse(Int, target_id), parse(Int, center_id), et)
end


"""
    get_state_ephemerides(provider, target_id, center_id, et)

Query a target body's state relative to a center body using Ephemerides.jl.

This provider-only method is retained for backward compatibility and manually
chains common DE ephemeris point trees.  For arbitrary target/center pairs in the
dynamics, prefer the `FrameTransformations.FrameSystem` method below.
"""
function get_state_ephemerides(provider, target_id::Integer, center_id::Integer, et::Number)
    isnothing(provider) && error(
        "No Ephemerides.jl provider was supplied. Pass `ephemerides_provider` or `ephemerides_files` to HighFidelityEphemerisModelParameters."
    )

    return _ephem_vector6_with_fallback(provider, Int(center_id), Int(target_id), et)
end


function get_state_ephemerides(provider, target_id::String, center_id::String, et::Number)
    return get_state_ephemerides(provider, parse(Int, target_id), parse(Int, center_id), et)
end


"""
    ephemerides_axes_symbol(frame_name)

Map common SPICE frame names to FrameTransformations axes symbols.

SPICE treats `J2000` as the ICRF/J2000 inertial axes for the use cases in this
package, so the Ephemerides/FrameTransformations backend maps `"J2000"` to
`:ICRF`.
"""
function ephemerides_axes_symbol(frame_name::String)
    frame_upper = uppercase(frame_name)

    if frame_upper in ("J2000", "ICRF")
        return :ICRF
    elseif frame_upper == "EME2000"
        return :EME2000
    elseif frame_upper == "MOON_PA"
        return :MOON_PA
    else
        return Symbol(frame_name)
    end
end

ephemerides_axes_symbol(frame_name::Symbol) = frame_name
ephemerides_axes_symbol(frame_name::Integer) = Int(frame_name)


@inline _ephemerides_point_symbol(point::Integer) = Symbol("P$(Int(point))")


function _frame_has_point(frames, point)
    try
        return FrameTransformations.has_point(frames, point)
    catch
        return false
    end
end


function _try_add_axes!(frames, f::Function)
    try
        f()
    catch error
        # Ignore duplicate-registration errors, but surface all other failures.
        msg = sprint(showerror, error)
        if occursin("already registered", msg)
            return nothing
        end
        rethrow(error)
    end

    return nothing
end


function _try_add_point_ephemeris!(frames, provider, point::Int)
    point == 0 && return true
    _frame_has_point(frames, point) && return true

    try
        FrameTransformations.add_point_ephemeris!(
            frames,
            provider,
            _ephemerides_point_symbol(point),
            point,
        )
        return true
    catch
        return false
    end
end


function _register_ephemerides_points!(frames, provider)
    points = Int.(collect(Ephemerides.ephem_get_points(provider)))

    # The SSB is the root point and is registered manually before this helper.
    remaining = Set(filter(!=(0), points))

    # Common DE hierarchy: SSB children first, then planet centers/Moon/Earth.
    priority = [10; collect(1:9); 199; 299; 301; 399]

    for point in priority
        if point in remaining && _try_add_point_ephemeris!(frames, provider, point)
            delete!(remaining, point)
        end
    end

    # Generic fallback: keep trying points until all possible parent nodes have
    # been registered. This supports kernels beyond the common DE tree whenever
    # FrameTransformations can infer each point's parent from the provider.
    while !isempty(remaining)
        progressed = false

        for point in collect(remaining)
            if _try_add_point_ephemeris!(frames, provider, point)
                delete!(remaining, point)
                progressed = true
            end
        end

        if !progressed
            @warn "Some Ephemerides points could not be registered in the FrameTransformations graph" collect(remaining)
            break
        end
    end

    return frames
end


"""
    build_ephemerides_frame_system(provider, frame_PCPF=nothing)

Build a FrameTransformations frame system for Ephemerides-backed point and axes
transforms.

The frame system is built with order 2 so it supports both `vector3` and
`vector6` queries.  Ephemerides.jl only reads stored SPK/PCK records; point-chain
concatenation is handled through FrameTransformations.jl.
"""
function build_ephemerides_frame_system(provider, frame_PCPF::Union{Nothing,String}=nothing)
    isnothing(provider) && error(
        "No Ephemerides.jl provider was supplied. Pass `ephemerides_provider` or `ephemerides_files` to HighFidelityEphemerisModelParameters."
    )

    frames = FrameTransformations.FrameSystem{2,Float64}()

    FrameTransformations.add_axes_icrf!(frames)

    # EME2000 is useful when users request it explicitly, but not every
    # FrameTransformations version needs it. Ignore duplicate/unsupported issues
    # only when the function itself is unavailable.
    if isdefined(FrameTransformations, :add_axes_eme2000!)
        try
            FrameTransformations.add_axes_eme2000!(frames)
        catch error
            msg = sprint(showerror, error)
            occursin("already registered", msg) || rethrow(error)
        end
    end

    # Root point for the SPK point graph. The docs use ICRF axes ID 1.
    FrameTransformations.add_point!(frames, :SSB, 0, 1)
    _register_ephemerides_points!(frames, provider)

    if !isnothing(frame_PCPF)
        frame_symbol = ephemerides_axes_symbol(frame_PCPF)

        if frame_symbol == :MOON_PA
            FrameTransformations.add_axes_pa440!(frames, provider, frame_symbol)
        end
    end

    return frames
end


"""
    get_pos_ephemerides(frames, target_id, center_id, et; axes=:ICRF)

Query a target body's position relative to a center body through a populated
FrameTransformations frame system.  This is the preferred Ephemerides backend
query for arbitrary target/center pairs because FrameTransformations.jl performs
the point-chain concatenation that Ephemerides.jl intentionally does not do.
"""
function get_pos_ephemerides(
    frames::FrameTransformations.FrameSystem,
    target_id::Integer,
    center_id::Integer,
    et::Number;
    axes = :ICRF,
)
    axes_symbol = ephemerides_axes_symbol(axes)

    return FrameTransformations.vector3(
        frames,
        Int(center_id),
        Int(target_id),
        axes_symbol,
        et,
    )
end


function get_pos_ephemerides(
    frames::FrameTransformations.FrameSystem,
    target_id::String,
    center_id::String,
    et::Number;
    axes = :ICRF,
)
    return get_pos_ephemerides(
        frames,
        parse(Int, target_id),
        parse(Int, center_id),
        et;
        axes = axes,
    )
end


"""
    get_state_ephemerides(frames, target_id, center_id, et; axes=:ICRF)

Query a target body's state relative to a center body through a populated
FrameTransformations frame system.
"""
function get_state_ephemerides(
    frames::FrameTransformations.FrameSystem,
    target_id::Integer,
    center_id::Integer,
    et::Number;
    axes = :ICRF,
)
    axes_symbol = ephemerides_axes_symbol(axes)

    return FrameTransformations.vector6(
        frames,
        Int(center_id),
        Int(target_id),
        axes_symbol,
        et,
    )
end


function get_state_ephemerides(
    frames::FrameTransformations.FrameSystem,
    target_id::String,
    center_id::String,
    et::Number;
    axes = :ICRF,
)
    return get_state_ephemerides(
        frames,
        parse(Int, target_id),
        parse(Int, center_id),
        et;
        axes = axes,
    )
end


"""
    pxform_ephemerides(params, frame_from, frame_to, et)

Ephemerides.jl/FrameTransformations-backed replacement for

    SPICE.pxform(frame_from, frame_to, et)

for supported axes in `params.ephemerides_frame_system`.
"""
function pxform_ephemerides(params, frame_from::String, frame_to::String, et::Number)
    isnothing(params.ephemerides_frame_system) && error(
        "No Ephemerides.jl frame system was supplied. Pass `ephemerides_frame_system`, or pass `ephemerides_files`/`ephemerides_provider` together with a supported `frame_PCPF`."
    )

    axes_from = ephemerides_axes_symbol(frame_from)
    axes_to = ephemerides_axes_symbol(frame_to)

    rotation = FrameTransformations.rotation3(
        params.ephemerides_frame_system,
        axes_from,
        axes_to,
        et,
    )

    return Matrix(rotation[1])
end